---
substitutions:
  gpio_led: GPIO2
  # For gas one of: CCF, ft³, m³
  volume_unit: 'ft³'
  # The most common value in US seems to be 0.125 ft³
  # If you modify the volume_unit, modify this too,
  # just search on Google: 0.125 ft³ to CCF (or whatever unit you selected)
  volume_per_half_rotation_initial_value: '0.125'
  flow_update_interval_seconds: '30'

packages:
  gas_meter: !include
    file: esphome-magnetometer.yaml
    vars:
      device_class: 'gas'
      device_icon: 'mdi:meter-gas'

switch:
  # LED flashes faster/slower as magnet rotates on water meter
  - platform: gpio
    id: led
    pin:
      number: ${gpio_led}
      inverted: true
